version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "6543:5432"
    volumes:
     - postgresDB:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
      
volumes:
  postgresDB:
  redisDB:
